name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t my-app .

    - name: Run Container
      run: docker run -d -p 5000:5000 my-app

    - name: Login to DockerHub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Image
      run: |
          docker build -t quratain/my-app .
          docker push quratain/my-app